repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - LICENSE_HEADER.txt
          - --comment-style
          - "#"
